### ISSUE TITLE
Pypercard behaves weirdly in the PyScript.com preview when it's included as a package dependency

### ISSUE THREAD

**Issue by MarieRoald** [pyscript/pypercard#56]
Pypercard behaves weirdly in the PyScript.com preview when it's included as a package dependency

I tried to follow this documentation example: https://pypercard.readthedocs.io/en/latest/tutorial3.html#interactive-hello

However, the project fails to start running (see traceback below) in the PyScript.com preview (see screenshot below). I haven't found the exact problem, but the code crashes immediately after the `App.start()` method is called, regardless if I include any transitions. Also, if instead of including pypercard as a package dependency, I explicitly add a [[fetch]]-block and link the modules hosted on GitHub pages, it works. 

Here is a [PyScript](https://9a88206f-0390-4f47-ba0f-1901ee181974.pyscriptapps.com/e983a9dc-50cc-4593-848c-25996024ba08/latest/) (URL: https://9a88206f-0390-4f47-ba0f-1901ee181974.pyscriptapps.com/e983a9dc-50cc-4593-848c-25996024ba08/latest/) that shows it not working (press the view code button to see the error).

Here is the exception traceback:
```raw
Traceback (most recent call last):
  File "/home/pyodide/pyscript/_internal.py", line 104, in run_pyscript
    result = eval_code(code, globals=__main__.__dict__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 468, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 310, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 36, in <module>
  File "/lib/python3.11/site-packages/pypercard/core.py", line 761, in start
    self.machine.start(card_name)
  File "/lib/python3.11/site-packages/pypercard/state_machine.py", line 181, in start
    self._enter_state(self.current_state)
  File "/lib/python3.11/site-packages/pypercard/state_machine.py", line 233, in _enter_state
    state.call_on_enter_hooks(self)
  File "/lib/python3.11/site-packages/pypercard/state_machine.py", line 265, in call_on_enter_hooks
    hook(machine)
  File "/lib/python3.11/site-packages/pypercard/core.py", line 871, in <lambda>
    on_enter=[lambda machine: self.show_card(card)],
                              ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pypercard/core.py", line 515, in show_card
    card.show()
  File "/lib/python3.11/site-packages/pypercard/core.py", line 215, in show
    html = self.template.format(**self.app.datastore)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pypercard/datastore.py", line 147, in __getitem__
    return json.loads(self.store.getItem(key))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

And here is a screenshot: 
![image](https://github.com/pyscript/pypercard/assets/3594989/7d9be945-b0e7-47c0-ba04-a9dbe31c4a00)

Tested browsers (Windows):
 * Firefox 114.0.2 (64-bit)
 * Vivaldi 6.1.3035.84 (Stable channel) (64-bit)

**Comment by MarieRoald** [comment]
I wondered if the iframe in the PyScript editor somehow confused Pypercard, but that didn't seem to be the case when I tried locally.

After investigating it further, I found some even weirder behaviour. I checked the URL of the iframe embedded in the PyScript.com editor and that code failed whenever I opened that URL in a browser where I was signed into PyScript.com (I tested with both my and my partner's user), and succeeded whenever I used a private window or a browser where I was not signed in. 

So it's beginning to look more and more like it might be a PyScript.com problem.

**Comment by fpliger** [comment]
We fixed a very very similar issue (if not this one). I'll try to check out, might be that we just didn't release after fixing the issue

**Comment by fpliger** [comment]
@ntoll .. I think this has been fixed and it's only missing a new release. Can you confirm?
